# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba4971232111935efbe1e7c0d3dd752752512ed165e14fb5038bb55438bf227f6ea6e11f63eef2766f4f37604b8aa26f3dd13ab18160af1732e17910be60939

test:
  secret_key_base: aa687c262d78e9ce4177660b81f4ebe960ff8d39b573efa6739d58c81ba59b58d825b64b3b9c877b1e36bb10d26ff0683bbbd4281706fec7b8687c1fc0f0984f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
